# Generated by Django 2.0 on 2017-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171221_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='action',
            field=models.CharField(choices=[('0', '其他'), ('1', '新建'), ('2', '删除'), ('3', '修改'), ('4', '查询'), ('5', '审核SKU'), ('6', '提交到货预报'), ('7', '审核到货预报'), ('8', '入库'), ('9', '出库')], max_length=8, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='prepayrecord',
            name='instruction',
            field=models.CharField(blank=True, default='', help_text='请输入费用发生的详细原因，便于后期记录查找', max_length=30, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='prepayrecord',
            name='sum',
            field=models.DecimalField(decimal_places=2, help_text='请输入发生金额，扣款以负数表示，如：-12.5', max_digits=7, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='prepayrecord',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '预存款'), (2, '入仓费'), (3, '操作费'), (4, '订单运费'), (5, '仓租'), (6, '退件接受检查费'), (7, '其他')], help_text='请在预设的费用类别中选择发生的费用所属的类别', verbose_name='费用类别'),
        ),
    ]
