# Generated by Django 2.0 on 2017-12-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171222_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyvolumeperday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='当日体积')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company', verbose_name='客户公司')),
            ],
            options={
                'verbose_name': '公司每日库存体积',
                'verbose_name_plural': '公司每日库存体积',
            },
        ),
    ]
