# Generated by Django 2.0 on 2018-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180101_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvolumeperday',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='当日体积'),
        ),
    ]
