# Generated by Django 2.0 on 2018-02-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180107_1958'),
        ('depot', '0012_auto_20180131_0207'),
        ('account', '0010_auto_20180107_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvolumeperday',
            name='out',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='当日出库体积'),
        ),
        migrations.AddField(
            model_name='prepayrecord',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
        migrations.AddField(
            model_name='prepayrecord',
            name='reject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Reject'),
        ),
        migrations.AddField(
            model_name='prepayrecord',
            name='transorder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Transorder'),
        ),
        migrations.AlterField(
            model_name='companyvolumeperday',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='当日库存体积'),
        ),
        migrations.AlterField(
            model_name='prepayrecord',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '预存款'), (2, '入仓费'), (3, '操作费'), (4, '订单运费'), (5, '仓租'), (6, '退件接受检查费'), (7, '退件相关'), (8, '其他')], help_text='请在预设的费用类别中选择发生的费用所属的类别', verbose_name='费用类别'),
        ),
    ]
