# Generated by Django 2.0 on 2017-12-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='unit',
        ),
        migrations.AddField(
            model_name='count',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Unit'),
        ),
        migrations.AddField(
            model_name='sku',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：cm厘米，保留两位小数点', max_digits=6, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='sku',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：cm厘米，保留两位小数点', max_digits=6, verbose_name='长度'),
        ),
        migrations.AddField(
            model_name='sku',
            name='leo_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='雷欧海外仓SKU编码'),
        ),
        migrations.AddField(
            model_name='sku',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：cm厘米，保留两位小数点', max_digits=6, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='img',
            field=models.ImageField(blank=True, upload_to='sku_img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：欧元，保留两位小数点', max_digits=8, verbose_name='申报价值'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='status',
            field=models.CharField(choices=[('0', '待审核'), ('1', '已审核'), ('2', '拒收')], default=0, max_length=12, verbose_name='Sku状态'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：m3立方米，保留两位小数点', max_digits=6, verbose_name='体积'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='单位：kg千克，保留三位小数点', max_digits=6, verbose_name='重量'),
        ),
    ]
