# Generated by Django 2.0 on 2017-12-20 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_auto_20171220_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('1', '入库'), ('2', '出库')], max_length=2, verbose_name='变动类型')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='变动时间')),
                ('depot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Depot', verbose_name='仓库')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Sku', verbose_name='SKU')),
            ],
        ),
        migrations.AddField(
            model_name='transorder',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='count',
            name='depot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Depot', verbose_name='所属仓库'),
        ),
        migrations.AlterField(
            model_name='count',
            name='freeze',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='冻结'),
        ),
        migrations.AlterField(
            model_name='count',
            name='normal',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='正常'),
        ),
        migrations.AlterField(
            model_name='count',
            name='other',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='count',
            name='preparing_in',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='待入库'),
        ),
        migrations.AlterField(
            model_name='count',
            name='preparing_out',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='待出库'),
        ),
        migrations.AlterField(
            model_name='count',
            name='short',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='缺货'),
        ),
        migrations.AlterField(
            model_name='count',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Sku', verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='count',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Unit', verbose_name='所属库位'),
        ),
        migrations.AlterField(
            model_name='customerlevelfee',
            name='reject_check_fee',
            field=models.DecimalField(decimal_places=2, help_text='请输入正数，输入负数会导致计算错误，保留两位小数', max_digits=5, verbose_name='退件接收检查费'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='预计到货数量'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='check',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Sku', verbose_name='到货SKU'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='transorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.Transorder', verbose_name='预计到货货物清单'),
        ),
        migrations.AlterField(
            model_name='skutypefee',
            name='in_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='请输入正数，输入负数会导致计算错误，保留两位小数', max_digits=5, verbose_name='入仓费'),
        ),
        migrations.AlterField(
            model_name='skutypefee',
            name='operation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='请输入正数，输入负数会导致计算错误，保留两位小数', max_digits=5, verbose_name='操作费'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='value_all',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='货值总计'),
        ),
    ]
