# Generated by Django 2.0 on 2017-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_auto_20171221_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='品类'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='SKU名称-中文'),
        ),
    ]
