# Generated by Django 2.0 on 2017-12-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20171223_0204'),
        ('depot', '0004_auto_20171222_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storagefee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='请输入计算仓租的月份，必须是1-12的正整数，且不能重复', unique=True, verbose_name='月份')),
                ('free_ratio', models.PositiveSmallIntegerField(help_text='正整数，代表0到此值的区间', verbose_name='小于此值免租的区间')),
                ('high_ratio', models.PositiveSmallIntegerField(help_text='正整数，代表大于此值的区间', verbose_name='大于此值按体积来计算的区间')),
            ],
        ),
        migrations.AddField(
            model_name='customerlevelfee',
            name='storage_fee',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='请输入正整数，此数值用于计算每月每立方米仓租费', verbose_name='仓租'),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Company', verbose_name='客户公司'),
        ),
        migrations.AlterField(
            model_name='customerlevelfee',
            name='reject_check_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='每单退件收取的接收检查费，请输入正数，输入负数会导致计算错误，保留两位小数', max_digits=5, verbose_name='退件接收检查费'),
        ),
    ]
