# Generated by Django 2.0 on 2018-01-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0006_auto_20171231_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlevelfee',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Level', verbose_name='客户等级'),
        ),
    ]
