# Generated by Django 2.0 on 2018-01-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0007_auto_20180101_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockchange',
            name='instruction',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='变动说明'),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='operate_style',
            field=models.CharField(choices=[('1', '系统'), ('2', '人工')], default=1, max_length=2, verbose_name='操作方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='count',
            name='depot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='depot.Depot', verbose_name='所属仓库'),
        ),
        migrations.AlterField(
            model_name='count',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depot.Sku', verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='客户SKU编码'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='change_type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '待入库'), ('4', '收货'), ('5', '其他')], max_length=2, verbose_name='变动类型'),
        ),
    ]
