# Generated by Django 2.0 on 2018-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0008_auto_20180101_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：米，保留2位小数点', max_digits=6, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：米，保留2位小数点', max_digits=6, verbose_name='长度'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：欧元，保留2位小数点', max_digits=8, verbose_name='申报价值'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, help_text='单位：m³立方米，保留6位小数点', max_digits=8, verbose_name='体积'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='单位：kg千克，保留3位小数点', max_digits=6, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='单位：米，保留2位小数点', max_digits=6, verbose_name='宽度'),
        ),
    ]
