# Generated by Django 2.0 on 2018-01-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0010_auto_20180107_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='SKU名称-中文'),
        ),
    ]
