# Generated by Django 2.0 on 2018-01-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0011_auto_20180112_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transorder',
            name='depot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Depot', verbose_name='目标仓库'),
        ),
    ]
