# Generated by Django 2.0 on 2018-05-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0012_auto_20180131_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='change_type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '待入库'), ('4', '收货'), ('5', '其他'), ('6', '取消订单')], max_length=2, verbose_name='变动类型'),
        ),
    ]
