# Generated by Django 2.0 on 2017-12-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(default='', max_length=10, unique=True, verbose_name='邮编')),
            ],
        ),
        migrations.RenameField(
            model_name='reject',
            old_name='order_code',
            new_name='reject_code',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='final_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='final_weight',
        ),
        migrations.AddField(
            model_name='reject',
            name='over_time',
            field=models.DateTimeField(auto_now=True, verbose_name='退件完结时间'),
        ),
        migrations.AddField(
            model_name='reject',
            name='stock_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='退单仓储费'),
        ),
        migrations.AddField(
            model_name='reject',
            name='stock_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='退单储存时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_delivery_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='最终运费'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='最终重量'),
        ),
        migrations.AlterField(
            model_name='ordercontain',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='ordercontain',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ordercontain',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='ordercontain',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Sku', verbose_name='SKU名称'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '退件接收'), ('2', '完结')], default='1', max_length=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='rejectcontain',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='退件数量'),
        ),
        migrations.AlterField(
            model_name='rejectcontain',
            name='reject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Reject', verbose_name='推荐单号'),
        ),
        migrations.AlterField(
            model_name='rejectcontain',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Sku', verbose_name='退件SKU'),
        ),
    ]
