# Generated by Django 2.0 on 2017-12-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171222_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderspecial',
            options={'verbose_name': '特殊地区邮编', 'verbose_name_plural': '特殊地区邮编'},
        ),
    ]
