# Generated by Django 2.0 on 2017-12-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20171222_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='instruction',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
    ]
