# Generated by Django 2.0 on 2018-01-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20171231_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.Depot', verbose_name='出货仓库'),
        ),
    ]
