# Generated by Django 2.0 on 2018-02-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180107_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_address1',
            field=models.CharField(max_length=200, verbose_name='消费者地址1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_address2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='消费者地址2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_city',
            field=models.CharField(max_length=80, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_country',
            field=models.CharField(max_length=80, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_county',
            field=models.CharField(default='', max_length=80, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='消费者电子邮箱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_full_name',
            field=models.CharField(max_length=100, verbose_name='消费者姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_phone_number',
            field=models.CharField(max_length=50, verbose_name='消费者联系电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_postcode',
            field=models.CharField(max_length=20, verbose_name='消费者邮编'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(default='', max_length=80, verbose_name='物流单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_record_number',
            field=models.CharField(max_length=80, verbose_name='客户销售平台订单号'),
        ),
    ]
